// ============================================================
// CTF TASKS DEFAULT DATA
// These are the 15 tasks from the CyberBrew workshop scenario.
// Admin can edit points, images, and files per event.
// ============================================================

const CTF_TASKS_TEMPLATE = [
  {
    id: 1,
    stage: "ETAP 1",
    stageName: "Zasłona Dymna (Atak Replay na Warzelni)",
    stageNameEn: "Smoke Screen (Replay Attack on Brewery)",
    name: "Lokalizacja (Wymiar A - Pozycja Purdue)",
    nameEn: "Location (Dimension A - Purdue Position)",
    narrative: "Operator warzelni zgłasza krytyczny problem: HMI (panel dotykowy) pokazuje stabilne 72°C w kadzi, ale fizyczny, analogowy termometr na rurze wskazuje 95°C. System SCADA milczy, nie ma żadnych alarmów. Zespół Incident Response (Wy) wkracza do akcji.",
    narrativeEn: "The brewery operator reports a critical issue: the HMI (touch panel) shows a stable 72°C in the vat, but the physical analog thermometer on the pipe reads 95°C. The SCADA system is silent — no alarms. The Incident Response team (you) springs into action.",
    context: "Zanim cokolwiek odłączycie, musicie zmapować teren.",
    contextEn: "Before disconnecting anything, you need to map the terrain.",
    question: "Na którym poziomie modelu Purdue znajduje się oszukiwany panel HMI, z którego korzysta operator na hali?",
    questionEn: "At which level of the Purdue model is the spoofed HMI panel that the operator on the floor uses?",
    format: "FLAG{Cyfra}",
    answer: "FLAG{2}",
    points: 100,
    images: [],
    files: []
  },
  {
    id: 2,
    stage: "ETAP 1",
    stageName: "Zasłona Dymna (Atak Replay na Warzelni)",
    stageNameEn: "Smoke Screen (Replay Attack on Brewery)",
    name: "Analiza Ruchu (Port)",
    nameEn: "Traffic Analysis (Port)",
    narrative: "Operator warzelni zgłasza krytyczny problem: HMI (panel dotykowy) pokazuje stabilne 72°C w kadzi, ale fizyczny, analogowy termometr na rurze wskazuje 95°C. System SCADA milczy, nie ma żadnych alarmów. Zespół Incident Response (Wy) wkracza do akcji.",
    narrativeEn: "The brewery operator reports a critical issue: the HMI shows a stable 72°C, but the physical analog thermometer reads 95°C. No SCADA alarms. The IR team springs into action.",
    context: "Otrzymujecie zrzut ruchu sieciowego (PCAP) z przełącznika (switcha) podłączonego do panelu HMI.",
    contextEn: "You receive a network traffic dump (PCAP) from the switch connected to the HMI panel.",
    question: "Analizujecie ruch TCP. Na jakim docelowym porcie komunikuje się HMI ze sterownikiem PLC, wykorzystując standardowy protokół przemysłowy widoczny w logach?",
    questionEn: "You analyze TCP traffic. On which destination port does the HMI communicate with the PLC controller using the standard industrial protocol visible in the logs?",
    format: "FLAG{Numer_Portu}",
    answer: "FLAG{502}",
    points: 100,
    images: [],
    files: []
  },
  {
    id: 3,
    stage: "ETAP 1",
    stageName: "Zasłona Dymna (Atak Replay na Warzelni)",
    stageNameEn: "Smoke Screen (Replay Attack on Brewery)",
    name: "Dekodowanie Payloadu (Hex)",
    nameEn: "Payload Decoding (Hex)",
    narrative: "",
    narrativeEn: "",
    context: "W Wiresharku widzicie podejrzaną serię identycznych pakietów Response: Trans: 501; Unit: 1; Func: 3; Data: 02 d0.",
    contextEn: "In Wireshark you see a suspicious series of identical packets Response: Trans: 501; Unit: 1; Func: 3; Data: 02 d0.",
    question: "Wartość 02 d0 w systemie szesnastkowym (Hex) to zamrożona temperatura (przeskalowana x10). Jaką temperaturę w stopniach Celsjusza haker wstrzykuje na ekran HMI?",
    questionEn: "The value 02 d0 in hexadecimal (Hex) is a frozen temperature (scaled x10). What temperature in Celsius is the hacker injecting onto the HMI screen?",
    format: "FLAG{Wartość.Dziesiętna}",
    answer: "FLAG{72.0}",
    points: 150,
    images: [],
    files: []
  },
  {
    id: 4,
    stage: "ETAP 1",
    stageName: "Zasłona Dymna (Atak Replay na Warzelni)",
    stageNameEn: "Smoke Screen (Replay Attack on Brewery)",
    name: "Krytyczność (Wymiar C - Impact)",
    nameEn: "Criticality (Dimension C - Impact)",
    narrative: "",
    narrativeEn: "",
    context: "HMI jest oszukiwane, a rzeczywista temperatura rośnie.",
    contextEn: "The HMI is being spoofed, and the actual temperature is rising.",
    question: "Zgodnie z analizą ryzyka, jaki jest główny wektor wpływu biznesowego (Krytyczność), jeśli kadź warzelna ulegnie rozszczelnieniu pod wpływem ciśnienia? (Wybierz: FINANCIAL, SAFETY, REPUTATION).",
    questionEn: "According to risk analysis, what is the main business impact vector (Criticality) if the brewing vat ruptures due to pressure? (Choose: FINANCIAL, SAFETY, REPUTATION).",
    format: "FLAG{SŁOWO}",
    answer: "FLAG{SAFETY}",
    points: 100,
    images: [],
    files: []
  },
  {
    id: 5,
    stage: "ETAP 1",
    stageName: "Zasłona Dymna (Atak Replay na Warzelni)",
    stageNameEn: "Smoke Screen (Replay Attack on Brewery)",
    name: "Mitygacja Operacyjna",
    nameEn: "Operational Mitigation",
    narrative: "",
    narrativeEn: "",
    context: "Nie możecie zrestartować sieci, bo proces warzenia trwa.",
    contextEn: "You cannot restart the network because the brewing process is ongoing.",
    question: "Jaka jest najbezpieczniejsza metoda weryfikacji parametrów procesu (tzw. \"Out-of-band\"), na której powinien teraz polegać operator?",
    questionEn: "What is the safest method for verifying process parameters (the so-called \"Out-of-band\" method) that the operator should rely on now?",
    format: "FLAG{SŁOWO}",
    answer: "FLAG{ANALOG}",
    points: 100,
    images: [],
    files: []
  },
  {
    id: 6,
    stage: "ETAP 2",
    stageName: "Prawdziwy Cel (Brewery Incident Response)",
    stageNameEn: "The Real Target (Brewery Incident Response)",
    name: "Pivot (Śledztwo w logach)",
    nameEn: "Pivot (Log Investigation)",
    narrative: "Uratowaliście warzelnię, odcinając skompromitowany panel HMI i przechodząc na sterowanie ręczne. Jednak analiza logów IDS wykazuje, że Atak Replay był tylko dywersją. Haker wykorzystał zamieszanie, aby z sieci biurowej (IT) dostać się głębiej do sieci OT – tym razem atakując linię rozlewniczą (Bottling Line).",
    narrativeEn: "You saved the brewery by isolating the compromised HMI and switching to manual control. However, IDS log analysis shows that the Replay Attack was only a diversion. The hacker exploited the confusion to move from the corporate (IT) network deeper into the OT network — this time targeting the bottling line.",
    context: "IDS wyłapał skanowanie sieci produkcyjnej z nietypowego adresu.\nFragment logu: ALERT: TCP SYN SCAN. SRC: 10.20.5.50 DST: 10.10.20.0/24",
    contextEn: "IDS detected a scan of the production network from an unusual address.\nLog excerpt: ALERT: TCP SYN SCAN. SRC: 10.20.5.50 DST: 10.10.20.0/24",
    question: "Jaki jest adres IP zarażonej maszyny w sieci biurowej, która posłużyła jako punkt przesiadkowy (pivot) dla hakera?",
    questionEn: "What is the IP address of the infected machine in the corporate network that served as a pivot point for the hacker?",
    format: "FLAG{Adres_IP}",
    answer: "FLAG{10.20.5.50}",
    points: 100,
    images: [],
    files: []
  },
  {
    id: 7,
    stage: "ETAP 2",
    stageName: "Prawdziwy Cel (Brewery Incident Response)",
    stageNameEn: "The Real Target (Brewery Incident Response)",
    name: "Klasyfikacja Aktywa (Wymiar A - Pozycja Purdue)",
    nameEn: "Asset Classification (Dimension A - Purdue Position)",
    narrative: "",
    narrativeEn: "",
    context: "Haker zaatakował docelowo sterownik PLC kontrolujący prędkość taśmociągu rozlewniczego.",
    contextEn: "The hacker specifically targeted the PLC controller controlling the speed of the bottling line conveyor.",
    question: "Na którym poziomie modelu Purdue operuje ten docelowy sterownik PLC?",
    questionEn: "At which level of the Purdue model does this target PLC controller operate?",
    format: "FLAG{Cyfra}",
    answer: "FLAG{1}",
    points: 100,
    images: [],
    files: []
  },
  {
    id: 8,
    stage: "ETAP 2",
    stageName: "Prawdziwy Cel (Brewery Incident Response)",
    stageNameEn: "The Real Target (Brewery Incident Response)",
    name: "Kontekst Operacyjny (Wymiar B - Funkcja)",
    nameEn: "Operational Context (Dimension B - Function)",
    narrative: "",
    narrativeEn: "",
    context: "Aby ocenić ryzyko, musicie zrozumieć, co robi ta maszyna.",
    contextEn: "To assess the risk, you need to understand what this machine does.",
    question: "Mając do wyboru funkcje: BREWING, COOLING, PACKAGING, UTILITIES – do jakiej kategorii przypiszesz ten sterownik PLC?",
    questionEn: "Given the functions: BREWING, COOLING, PACKAGING, UTILITIES – which category does this PLC controller belong to?",
    format: "FLAG{SŁOWO}",
    answer: "FLAG{PACKAGING}",
    points: 100,
    images: [],
    files: []
  },
  {
    id: 9,
    stage: "ETAP 2",
    stageName: "Prawdziwy Cel (Brewery Incident Response)",
    stageNameEn: "The Real Target (Brewery Incident Response)",
    name: "Wektor Ataku (Funkcja Modbus)",
    nameEn: "Attack Vector (Modbus Function)",
    narrative: "",
    narrativeEn: "",
    context: "Przechwycono pakiet z zarażonego komputera do PLC linii rozlewniczej: Function Code: 16 (0x10) - Write Multiple Registers.",
    contextEn: "A packet was intercepted from the infected computer to the bottling line PLC: Function Code: 16 (0x10) - Write Multiple Registers.",
    question: "Jakiej funkcji używa haker? Podaj jej decymalny (dziesiętny) numer identyfikacyjny protokołu Modbus.",
    questionEn: "What function is the hacker using? Give its decimal identification number in the Modbus protocol.",
    format: "FLAG{Liczba}",
    answer: "FLAG{16}",
    points: 100,
    images: [],
    files: []
  },
  {
    id: 10,
    stage: "ETAP 2",
    stageName: "Prawdziwy Cel (Brewery Incident Response)",
    stageNameEn: "The Real Target (Brewery Incident Response)",
    name: "Złośliwy Payload (Prędkość taśmy)",
    nameEn: "Malicious Payload (Belt Speed)",
    narrative: "",
    narrativeEn: "",
    context: "W pakiecie Write Multiple Registers haker nadpisuje rejestr odpowiedzialny za prędkość taśmociągu (RPM). Wartość w pakiecie to 0x0BB8.",
    contextEn: "In the Write Multiple Registers packet, the hacker overwrites the register responsible for conveyor belt speed (RPM). The value in the packet is 0x0BB8.",
    question: "Jaką nową prędkość (w dziesiętnych RPM) haker próbuje ustawić, aby butelki zaczęły spadać z taśmy?",
    questionEn: "What new speed (in decimal RPM) is the hacker trying to set to make bottles fall off the belt?",
    format: "FLAG{Liczba}",
    answer: "FLAG{3000}",
    points: 150,
    images: [],
    files: []
  },
  {
    id: 11,
    stage: "ETAP 2",
    stageName: "Prawdziwy Cel (Brewery Incident Response)",
    stageNameEn: "The Real Target (Brewery Incident Response)",
    name: "Wpływ Biznesowy (Wymiar C - Krytyczność)",
    nameEn: "Business Impact (Dimension C - Criticality)",
    narrative: "",
    narrativeEn: "",
    context: "Rozbite butelki to strata, ale nie ma zagrożenia wybuchem.",
    contextEn: "Broken bottles are a loss, but there is no risk of explosion.",
    question: "W odróżnieniu od warzelni, jaki jest główny wektor Krytyczności dla zniszczonego produktu na linii rozlewniczej? (Wybierz: SAFETY, FINANCIAL, COMPLIANCE).",
    questionEn: "Unlike the brewery, what is the main Criticality vector for destroyed product on the bottling line? (Choose: SAFETY, FINANCIAL, COMPLIANCE).",
    format: "FLAG{SŁOWO}",
    answer: "FLAG{FINANCIAL}",
    points: 100,
    images: [],
    files: []
  },
  {
    id: 12,
    stage: "ETAP 2",
    stageName: "Prawdziwy Cel (Brewery Incident Response)",
    stageNameEn: "The Real Target (Brewery Incident Response)",
    name: "Kalkulacja Ryzyka (Risk Score)",
    nameEn: "Risk Calculation (Risk Score)",
    narrative: "",
    narrativeEn: "",
    context: "Czas wyliczyć ostateczny Risk Score dla tego incydentu w oparciu o równanie:\nScore = AxBxC\nDane wejściowe: Poziom Purdue (A) = 3 (wartość wagi), Funkcja Packaging (B) = 3, Krytyczność Financial (C) = 4.",
    contextEn: "Time to calculate the final Risk Score for this incident based on the equation:\nScore = AxBxC\nInput data: Purdue Level (A) = 3 (weight value), Function Packaging (B) = 3, Criticality Financial (C) = 4.",
    question: "Ile wynosi wyliczony Risk Score?",
    questionEn: "What is the calculated Risk Score?",
    format: "FLAG{Liczba}",
    answer: "FLAG{36}",
    points: 150,
    images: [],
    files: []
  },
  {
    id: 13,
    stage: "ETAP 2",
    stageName: "Prawdziwy Cel (Brewery Incident Response)",
    stageNameEn: "The Real Target (Brewery Incident Response)",
    name: "Błąd Architektury (Analiza Firewalla)",
    nameEn: "Architecture Flaw (Firewall Analysis)",
    narrative: "",
    narrativeEn: "",
    context: "Zespół IT podesłał konfigurację firewalla brzegowego (IT/OT).",
    contextEn: "The IT team sent the configuration of the perimeter firewall (IT/OT).",
    question: "Który numer reguły (Line) pozwolił komputerowi z sieci IT na wstrzyknięcie złośliwych komend bezpośrednio do sterownika PLC?",
    questionEn: "Which rule number (Line) allowed the computer from the IT network to inject malicious commands directly into the PLC controller?",
    format: "FLAG{Liczba}",
    answer: "FLAG{20}",
    points: 150,
    images: [],
    files: []
  },
  {
    id: 14,
    stage: "ETAP 2",
    stageName: "Prawdziwy Cel (Brewery Incident Response)",
    stageNameEn: "The Real Target (Brewery Incident Response)",
    name: "Incident Containment (Izolacja)",
    nameEn: "Incident Containment (Isolation)",
    narrative: "",
    narrativeEn: "",
    context: "Musicie powstrzymać atak z sieci IT, pozwalając linii produkcyjnej dalej pracować autonomicznie.",
    contextEn: "You must stop the attack from the IT network while allowing the production line to continue operating autonomously.",
    question: "Jaką akcję techniczną na firewallu IT/OT należy wykonać natychmiast, aby zablokować hakera?",
    questionEn: "What technical action on the IT/OT firewall must be performed immediately to block the hacker?",
    format: "FLAG{SŁOWO}",
    answer: "FLAG{DENY}",
    points: 100,
    images: [],
    files: []
  },
  {
    id: 15,
    stage: "ETAP 2",
    stageName: "Prawdziwy Cel (Brewery Incident Response)",
    stageNameEn: "The Real Target (Brewery Incident Response)",
    name: "Lessons Learned (Długoterminowa naprawa)",
    nameEn: "Lessons Learned (Long-term Fix)",
    narrative: "",
    narrativeEn: "",
    context: "Raport po incydencie. Protokół Modbus TCP nie posiada szyfrowania ani uwierzytelniania, co ułatwiło oba ataki (Replay i wstrzykiwanie).",
    contextEn: "Post-incident report. The Modbus TCP protocol has no encryption or authentication, which facilitated both attacks (Replay and injection).",
    question: "Jaki nowoczesny standard komunikacji przemysłowej (skrót 5 liter, używający certyfikatów i wbudowanego bezpieczeństwa) browar powinien wdrożyć w przyszłości zamiast gołego Modbusa?",
    questionEn: "What modern industrial communication standard (5-letter abbreviation, using certificates and built-in security) should the brewery implement in the future instead of plain Modbus?",
    format: "FLAG{SKRÓT}",
    answer: "FLAG{OPC_UA}",
    points: 200,
    images: [],
    files: []
  }
];
